apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "10.26.0"
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    useStatefulSet: "true"    
    auth:
      enabled: true
      rootUser: root
      rootPassword: "mongodb"